trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformTaskV1@0
    inputs:
      provider: 'aws'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
      backendServiceAWS: 'aws-for-terraform'
      backendAWSBucketName: 'tf-backend-state-masala'
      backendAWSKey: 'kube-dev.tfstate'

    