trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - sh "git config --system core.longpaths true"
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub-dockerhub'
        repository: 'ssundaram1000/currency-exchange-azure-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    